### ISSUE TITLE
Fuck you,bitch

### ISSUE THREAD

**Issue by AnonF2ck** [AnimeSwap/docs#80]
植入者博客https://animeswap.org/
源服务器
ip16.163.205.112
https://16.163.205.112/
矿池端口
16.163.205.112:6666
16.163.205.112:7777
16.163.205.112:8888
16.163.205.112:9999
挖矿程序https://cloud.rtaki.com/upload/9833a1c3ffda63c9420479042f68ddfb.bin
Chinese:就你踏马在我服务器植入木马啊，我操你妈的，给你服务器DDOS了，傻逼东西
English:Just step on your horse and plant a Trojan virus in my server. Damn it, I attacked your server DDOS, you idiot.Son of the bitch.You are a bitch.
My email: hacker.F@qq.com

**Comment by Azard** [comment]
@AnonF2ck 植入者不是天池，天池只是被植入者用来连接的众多矿池之一，你找错攻击对象了
